### PR TITLE
Fix CLI: assign multiple IP addresses and use one network interface name

### LINKED ISSUE #499: Command line client doesn't seem to support multiple addresses
```
ERROR dg: Invalid assigned IP address in device configuration
```

### PR DESCRIPTION
**Pull request by moubctez**
Fixes #499 and #500

### CODE REVIEW

File: src-tauri/cli/src/bin/dg.rs [hunk 1]
```diff
@@ -607,48 +632,57 @@ async fn main() {
...
-                    error!("No CLI confioguration file found at \"{path}\". \
-                    Proceed with enrollment first using \"dg enroll -t <TOKEN> -u <URL>\" or pass a valid configuration file path using the \"--config\" option. Use \"dg --help\" to display all options.");
-                    return;
-                }
-                _ => {
-                    error!("Failed to load CLI configuration: {err}");
+            Err(err) => {
+                if let CliError::ConfigNotFound(path) = err {
+                    error!(
+                        "No CLI confioguration file found at \"{path}\". Proceed with \
```
Comment (t-aleksander) [inline src-tauri/cli/src/bin/dg.rs:651]:
```suggestion
                        "No CLI configuration file found at \"{path}\". Proceed with \
```

**Review by t-aleksander — APPROVED** [review]

**Review by filipslezaklab — APPROVED** [review]
